import React,{useState,useEffect}from 'react';import axios from 'axios';import Layout from '../../components/common/Layout';import toast from 'react-hot-toast';import{CheckCircle,XCircle,Eye}from 'lucide-react';import{useNavigate}from 'react-router-dom';
export default function ApprovalPending(){
  const[apps,setApps]=useState([]);const[loading,setLoading]=useState(true);const navigate=useNavigate();
  const load=()=>{setLoading(true);axios.get('/api/applications').then(r=>{setApps((r.data||[]).filter(a=>['submitted','under_review'].includes(a.status)));}).finally(()=>setLoading(false));};useEffect(load,[]);
  const upd=async(id,status,appId)=>{try{await axios.put(`/api/applications/${id}/status`,{status});toast.success(`${appId} ${status}`);load();}catch{toast.error('Failed');}};
  return(<Layout title="Approval Pending">
    <div className="page-hdr"><div><h1 className="page-title">Approval Pending</h1><p className="page-subtitle">{apps.length} applications awaiting action</p></div></div>
    <div className="card">{loading?<div className="loading-box"><div className="spinner"/></div>:(<div className="tbl-wrap"><table className="tbl"><thead><tr><th>Client ID</th><th>Organization</th><th>Client</th><th>Standard</th><th>Status</th><th>Auditor</th><th>Date</th><th>Actions</th></tr></thead><tbody>{apps.map(a=>(<tr key={a._id}><td><span className="mono">{a.client?.clientId||'—'}</span></td><td style={{fontWeight:600,maxWidth:160}}>{a.organizationName}</td><td style={{fontSize:13}}>{a.client?.name||'—'}</td><td><span className="badge bdg-info" style={{fontSize:10,background:'var(--primary-50)',color:'var(--primary-dark)',border:'1px solid var(--primary-200)'}}>{a.isoStandard}</span></td><td><span className={`badge bdg-${a.status}`}>{a.status?.replace(/_/g,' ')}</span></td><td style={{fontSize:13,color:'var(--gray-500)'}}>{a.assignedAuditor?.name||'—'}</td><td style={{fontSize:12,color:'var(--gray-400)'}}>{new Date(a.createdAt).toLocaleDateString()}</td><td><div className="tbl-actions"><button className="btn btn-ghost btn-sm" onClick={()=>navigate(`/admin/applications/${a._id}`)}><Eye size={13}/>View</button><button className="btn btn-sm" style={{background:'var(--green)',color:'white',border:'none',borderRadius:8,display:'flex',alignItems:'center',gap:4,padding:'5px 10px',fontSize:12,fontWeight:600,cursor:'pointer'}} onClick={()=>upd(a._id,'approved',a.applicationId)}><CheckCircle size={13}/>Approve</button><button className="btn btn-danger btn-sm" onClick={()=>upd(a._id,'rejected',a.applicationId)}><XCircle size={13}/>Reject</button></div></td></tr>))}{apps.length===0&&<tr><td colSpan={8} style={{textAlign:'center',padding:40,color:'var(--gray-400)'}}>🎉 No pending approvals</td></tr>}</tbody></table></div>)}</div>
  </Layout>);}
