import React,{useState,useEffect}from 'react';import axios from 'axios';import Layout from '../../components/common/Layout';import toast from 'react-hot-toast';import{Eye,Send,ClipboardCheck}from 'lucide-react';import{useNavigate}from 'react-router-dom';
export default function AuditStages({stage}){
  const[apps,setApps]=useState([]);const[loading,setLoading]=useState(true);const[modal,setModal]=useState(null);const[notes,setNotes]=useState('');const[saving,setSaving]=useState(false);const navigate=useNavigate();
  const statusKey=stage===1?'audit_stage1':'audit_stage2';const nextStatus=stage===1?'audit_stage2':'approved';
  const load=()=>{setLoading(true);axios.get('/api/applications').then(r=>{setApps((r.data||[]).filter(a=>a.status===statusKey||(stage===1&&a.status==='under_review')));}).finally(()=>setLoading(false));};useEffect(load,[]);
  const moveNext=async()=>{if(!notes.trim())return toast.error('Please enter audit notes');setSaving(true);try{await axios.put(`/api/applications/${modal._id}/status`,{status:nextStatus,notes});toast.success(`Moved to ${nextStatus.replace(/_/g,' ')}`);setModal(null);setNotes('');load();}catch{toast.error('Failed');}finally{setSaving(false);}};
  return(<Layout title={`Audit Stage ${stage}`}>
    <div className="page-hdr"><div><h1 className="page-title">Audit Stage {stage}</h1><p className="page-subtitle">{apps.length} applications in this stage</p></div></div>
    <div className="card">{loading?<div className="loading-box"><div className="spinner"/></div>:(<div className="tbl-wrap"><table className="tbl"><thead><tr><th>Client ID</th><th>Organization</th><th>Standard</th><th>Assigned Auditor</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>{apps.map(a=>(<tr key={a._id}><td><span className="mono">{a.client?.clientId||'—'}</span></td><td style={{fontWeight:600,maxWidth:180}}>{a.organizationName}</td><td style={{fontSize:12}}>{a.isoStandard}</td><td style={{fontSize:13}}>{a.assignedAuditor?.name||<span style={{color:'var(--gray-400)'}}>Unassigned</span>}</td><td><span className={`badge bdg-${a.status}`}>{a.status?.replace(/_/g,' ')}</span></td><td style={{fontSize:12,color:'var(--gray-400)'}}>{new Date(a.submittedAt||a.createdAt).toLocaleDateString()}</td><td><div className="tbl-actions"><button className="btn btn-ghost btn-sm" onClick={()=>navigate(`/admin/applications/${a._id}`)}><Eye size={13}/>View</button><button className="btn btn-primary btn-sm" onClick={()=>{setModal(a);setNotes('');}}><ClipboardCheck size={13}/>{stage===1?'Move to Stage 2':'Approve'}</button></div></td></tr>))}{apps.length===0&&<tr><td colSpan={7} style={{textAlign:'center',padding:40,color:'var(--gray-400)'}}>No applications in Stage {stage}</td></tr>}</tbody></table></div>)}</div>
    {modal&&(<div className="modal-bg" onClick={()=>setModal(null)}><div className="modal-box" onClick={e=>e.stopPropagation()}><div className="modal-head"><div className="modal-title">Stage {stage} Report — {modal.applicationId}</div><button className="modal-close" onClick={()=>setModal(null)}>✕</button></div><div className="modal-body"><p style={{fontSize:13,color:'var(--gray-500)',marginBottom:16}}>Organization: <strong>{modal.organizationName}</strong></p><div className="form-group"><label className="form-label">Audit Notes / Report *</label><textarea className="form-control" rows={5} value={notes} onChange={e=>setNotes(e.target.value)} placeholder={`Stage ${stage} audit findings…`}/></div></div><div className="modal-foot"><button className="btn btn-ghost" onClick={()=>setModal(null)}>Cancel</button><button className="btn btn-primary" onClick={moveNext} disabled={saving}>{saving?'Submitting…':<><Send size={14}/>Submit & {stage===1?'Move to Stage 2':'Approve'}</>}</button></div></div></div>)}
  </Layout>);}
