import React,{useState,useEffect}from 'react';import axios from 'axios';import Layout from '../../components/common/Layout';import toast from 'react-hot-toast';import{Download,Eye,Upload,FolderOpen,Search}from 'lucide-react';
const TYPE_COLORS={applicationForm:'#3b82f6',agreement:'#8b5cf6',auditReport:'#f59e0b',reviewReport:'#14b8a6',certificate:'#16a34a',document:'#f97316'};
export default function DMS(){
  const[docs,setDocs]=useState([]);const[apps,setApps]=useState([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const[modal,setModal]=useState(false);const[form,setForm]=useState({appId:'',docType:'document',file:null});const[saving,setSaving]=useState(false);
  const load=()=>{setLoading(true);Promise.all([axios.get('/api/documents'),axios.get('/api/applications')]).then(([d,a])=>{setDocs(d.data||[]);setApps(a.data||[]);}).finally(()=>setLoading(false));};useEffect(load,[]);
  const filtered=docs.filter(d=>{const q=search.toLowerCase();return!q||d.name?.toLowerCase().includes(q)||d.applicationId?.toLowerCase().includes(q);});
  const upload=async()=>{if(saving)return;if(!form.appId||!form.file)return toast.error('Select application and file');setSaving(true);try{const fd=new FormData();fd.append('document',form.file);fd.append('docType',form.docType);await axios.post(`/api/applications/${form.appId}/upload`,fd,{headers:{'Content-Type':'multipart/form-data'}});toast.success('Uploaded');setModal(false);load();}catch{toast.error('Upload failed');}finally{setSaving(false);}};
  return(<Layout title="Document Management">
    <div className="page-hdr"><div><h1 className="page-title">Document Management System</h1><p className="page-subtitle">{filtered.length} documents</p></div><button className="btn btn-primary" onClick={()=>setModal(true)}><Upload size={14}/>Upload Document</button></div>
    <div className="card" style={{marginBottom:20}}><div className="card-body" style={{padding:14}}><div className="search-wrap"><Search size={15} className="search-ico"/><input className="search-input" placeholder="Search documents…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div></div>
    <div className="card">{loading?<div className="loading-box"><div className="spinner"/></div>:(<div className="tbl-wrap"><table className="tbl"><thead><tr><th>Document</th><th>Application</th><th>Type</th><th>Uploaded By</th><th>Date</th><th>Actions</th></tr></thead><tbody>{filtered.map((d,i)=>(<tr key={i}><td><div style={{display:'flex',alignItems:'center',gap:8}}><FolderOpen size={13} style={{color:'var(--primary)',flexShrink:0}}/><span style={{fontWeight:600,fontSize:13}}>{d.name||d.originalName||'Document'}</span></div></td><td style={{fontFamily:'JetBrains Mono,monospace',fontSize:12}}>{d.applicationId}</td><td><span style={{fontSize:11,fontWeight:700,padding:'2px 8px',borderRadius:99,background:(TYPE_COLORS[d.docType]||'#f97316')+'18',color:TYPE_COLORS[d.docType]||'#f97316',border:`1px solid ${(TYPE_COLORS[d.docType]||'#f97316')}44`}}>{(d.docType||'document').replace(/([A-Z])/g,' $1')}</span></td><td style={{fontSize:13}}>{d.uploadedByName||'—'}</td><td style={{fontSize:12,color:'var(--gray-400)'}}>{d.uploadedAt?new Date(d.uploadedAt).toLocaleDateString():'—'}</td><td><div className="tbl-actions"><a href={d.path} target="_blank" rel="noreferrer" className="btn btn-ghost btn-sm"><Eye size={13}/>View</a><a href={d.path} download className="btn btn-secondary btn-sm"><Download size={13}/>Download</a></div></td></tr>))}{filtered.length===0&&<tr><td colSpan={6} style={{textAlign:'center',padding:40,color:'var(--gray-400)'}}>No documents found</td></tr>}</tbody></table></div>)}</div>
    {modal&&(<div className="modal-bg" onClick={()=>setModal(false)}><div className="modal-box" onClick={e=>e.stopPropagation()}><div className="modal-head"><div className="modal-title">Upload Document</div><button className="modal-close" onClick={()=>setModal(false)}>✕</button></div><div className="modal-body"><div className="form-group"><label className="form-label">Application *</label><select className="form-control" value={form.appId} onChange={e=>setForm(p=>({...p,appId:e.target.value}))}><option value="">— Select —</option>{apps.map(a=><option key={a._id} value={a._id}>{a.applicationId} — {a.organizationName}</option>)}</select></div><div className="form-group"><label className="form-label">Document Type</label><select className="form-control" value={form.docType} onChange={e=>setForm(p=>({...p,docType:e.target.value}))}>{['applicationForm','agreement','signedForm','auditReport','reviewReport','certificate','document'].map(t=><option key={t} value={t}>{t.replace(/([A-Z])/g,' $1')}</option>)}</select></div><div className="form-group"><label className="form-label">File *</label><input type="file" className="form-control" onChange={e=>setForm(p=>({...p,file:e.target.files[0]}))} accept=".pdf,.doc,.docx,.jpg,.png"/></div></div><div className="modal-foot"><button className="btn btn-ghost" onClick={()=>setModal(false)}>Cancel</button><button className="btn btn-primary" onClick={upload} disabled={saving}>{saving?'Uploading…':<><Upload size={14}/>Upload</>}</button></div></div></div>)}
  </Layout>);}
