import React,{useState,useEffect}from 'react';import axios from 'axios';import Layout from '../../components/common/Layout';import toast from 'react-hot-toast';import{Plus,Search,AlertTriangle}from 'lucide-react';
const TYPE_BADGES={'Major NC':'bdg-rejected','Minor NC':'bdg-under_review','OFI':'bdg-submitted','Observation':'bdg-info'};
export default function Observation(){
  const[obs,setObs]=useState([]);const[apps,setApps]=useState([]);const[loading,setLoading]=useState(true);const[modal,setModal]=useState(false);const[search,setSearch]=useState('');const[saving,setSaving]=useState(false);const[form,setForm]=useState({applicationId:'',type:'Minor NC',description:'',corrective_action:''});
  const load=()=>{setLoading(true);Promise.all([axios.get('/api/observations'),axios.get('/api/applications')]).then(([o,a])=>{setObs(o.data||[]);setApps(a.data||[]);}).finally(()=>setLoading(false));};useEffect(load,[]);
  const filtered=obs.filter(o=>{const q=search.toLowerCase();return!q||o.applicationId?.toLowerCase().includes(q)||o.description?.toLowerCase().includes(q);});
  const appByAppId=Object.fromEntries(apps.map(a=>[a.applicationId,a]));
  const save=async()=>{if(!form.applicationId||!form.description)return toast.error('Application and description required');setSaving(true);try{await axios.post('/api/observations',form);toast.success('Observation added');setModal(false);load();}catch{toast.error('Failed');}finally{setSaving(false);}};
  return(<Layout title="Observations">
    <div className="page-hdr"><div><h1 className="page-title">Observations</h1><p className="page-subtitle">{filtered.length} observations</p></div><button className="btn btn-primary" onClick={()=>{setForm({applicationId:'',type:'Minor NC',description:'',corrective_action:''});setModal(true);}}><Plus size={14}/>Add Observation</button></div>
    <div className="card" style={{marginBottom:20}}><div className="card-body" style={{padding:14}}><div className="search-wrap"><Search size={15} className="search-ico"/><input className="search-input" placeholder="Search…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div></div>
    <div className="card">{loading?<div className="loading-box"><div className="spinner"/></div>:(<div className="tbl-wrap"><table className="tbl"><thead><tr><th>Client ID</th><th>Type</th><th>Description</th><th>Corrective Action</th><th>Raised By</th><th>Date</th><th>Status</th></tr></thead><tbody>{filtered.map(o=>(<tr key={o._id}><td><span className="mono">{appByAppId[o.applicationId]?.client?.clientId||'—'}</span></td><td><span className={`badge ${TYPE_BADGES[o.type]||'bdg-info'}`}>{o.type}</span></td><td style={{maxWidth:240,fontSize:12}}>{o.description}</td><td style={{maxWidth:180,fontSize:12,color:'var(--gray-500)'}}>{o.corrective_action||'—'}</td><td style={{fontSize:13}}>{o.raisedByName||'—'}</td><td style={{fontSize:12,color:'var(--gray-400)'}}>{o.createdAt?new Date(o.createdAt).toLocaleDateString():'—'}</td><td><span className={`badge ${o.status==='Closed'?'bdg-certified':'bdg-under_review'}`}>{o.status||'Open'}</span></td></tr>))}{filtered.length===0&&<tr><td colSpan={7} style={{textAlign:'center',padding:40,color:'var(--gray-400)'}}>No observations yet</td></tr>}</tbody></table></div>)}</div>
    {modal&&(<div className="modal-bg" onClick={()=>setModal(false)}><div className="modal-box" onClick={e=>e.stopPropagation()}><div className="modal-head"><div className="modal-title">Add Observation</div><button className="modal-close" onClick={()=>setModal(false)}>✕</button></div><div className="modal-body"><div className="form-row"><div className="form-group"><label className="form-label">Application *</label><select className="form-control" value={form.applicationId} onChange={e=>setForm(p=>({...p,applicationId:e.target.value}))}><option value="">— Select —</option>{apps.map(a=><option key={a._id} value={a.applicationId}>{a.applicationId} — {a.organizationName}</option>)}</select></div><div className="form-group"><label className="form-label">Type</label><select className="form-control" value={form.type} onChange={e=>setForm(p=>({...p,type:e.target.value}))}>{['Major NC','Minor NC','OFI','Observation'].map(t=><option key={t}>{t}</option>)}</select></div></div><div className="form-group"><label className="form-label">Description *</label><textarea className="form-control" rows={3} value={form.description} onChange={e=>setForm(p=>({...p,description:e.target.value}))} placeholder="Describe the observation…"/></div><div className="form-group"><label className="form-label">Corrective Action</label><textarea className="form-control" rows={2} value={form.corrective_action} onChange={e=>setForm(p=>({...p,corrective_action:e.target.value}))} placeholder="Required corrective action…"/></div></div><div className="modal-foot"><button className="btn btn-ghost" onClick={()=>setModal(false)}>Cancel</button><button className="btn btn-primary" onClick={save} disabled={saving}>{saving?'Saving…':<><AlertTriangle size={14}/>Add</>}</button></div></div></div>)}
  </Layout>);}
