import React,{useState,useEffect}from 'react';import axios from 'axios';import Layout from '../../components/common/Layout';import toast from 'react-hot-toast';import{Plus,Edit,Trash2,Shield}from 'lucide-react';
const ALL_PERMS=['view_dashboard','view_applications','submit_application','manage_applications','assign_auditor','manage_users','view_reports','submit_audit_report','submit_review','approve_application','manage_certificates','manage_standards'];
export default function AdminRoles(){
  const[roles,setRoles]=useState([]);const[loading,setLoading]=useState(true);const[modal,setModal]=useState(null);const[saving,setSaving]=useState(false);const[deleting,setDeleting]=useState(false);const[form,setForm]=useState({name:'',permissions:[]});
  const load=()=>{setLoading(true);axios.get('/api/roles').then(r=>setRoles(r.data||[])).finally(()=>setLoading(false));};useEffect(load,[]);
  const toggle=p=>setForm(f=>({...f,permissions:f.permissions.includes(p)?f.permissions.filter(x=>x!==p):[...f.permissions,p]}));
  const save=async()=>{if(saving)return;if(!form.name)return toast.error('Role name required');setSaving(true);try{if(modal==='add')await axios.post('/api/roles',form);else await axios.put(`/api/roles/${modal._id}`,form);toast.success(modal==='add'?'Created':'Updated');setModal(null);load();}catch(e){toast.error(e.response?.data?.message||'Error');}finally{setSaving(false);}};
  const del=async id=>{if(deleting)return;if(!window.confirm('Delete?'))return;setDeleting(true);try{await axios.delete(`/api/roles/${id}`);toast.success('Deleted');load();}catch{toast.error('Failed');}finally{setDeleting(false);}};
  return(<Layout title="Role Management">
    <div className="page-hdr"><div><h1 className="page-title">Role Management</h1><p className="page-subtitle">Define roles & permissions</p></div><button className="btn btn-primary" onClick={()=>{setForm({name:'',permissions:[]});setModal('add');}}><Plus size={14}/>Add Role</button></div>
    {loading?<div className="loading-box"><div className="spinner"/></div>:(<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(260px,1fr))',gap:16}}>{roles.map(r=>(<div key={r._id} className="card" style={{marginBottom:0}}><div className="card-hdr"><div className="card-title"><Shield size={14}/>{r.name}</div><div style={{display:'flex',gap:6}}><button className="btn btn-ghost btn-sm" onClick={()=>{setForm({name:r.name,permissions:r.permissions||[]});setModal(r);}}><Edit size={12}/></button><button className="btn btn-danger btn-sm" onClick={()=>del(r._id)} disabled={deleting}><Trash2 size={12}/></button></div></div><div className="card-body"><p style={{fontSize:12,color:'var(--gray-400)',marginBottom:10}}>Users: <strong style={{color:'var(--text-1)'}}>{r.userCount||0}</strong></p><div style={{display:'flex',flexWrap:'wrap',gap:5}}>{(r.permissions||[]).map(p=>(<span key={p} style={{fontSize:10,background:'var(--primary-50)',color:'var(--primary-dark)',border:'1px solid var(--primary-200)',padding:'2px 7px',borderRadius:99,fontWeight:600}}>{p.replace(/_/g,' ')}</span>))}{(!r.permissions||r.permissions.length===0)&&<span style={{fontSize:12,color:'var(--gray-400)'}}>No permissions set</span>}</div></div></div>))}{roles.length===0&&<p style={{color:'var(--gray-400)',fontSize:13}}>No roles yet.</p>}</div>)}
    {modal&&(<div className="modal-bg" onClick={()=>setModal(null)}><div className="modal-box" style={{maxWidth:580}} onClick={e=>e.stopPropagation()}><div className="modal-head"><div className="modal-title">{modal==='add'?'Add Role':'Edit Role'}</div><button className="modal-close" onClick={()=>setModal(null)}>✕</button></div><div className="modal-body"><div className="form-group"><label className="form-label">Role Name *</label><input className="form-control" value={form.name} onChange={e=>setForm(p=>({...p,name:e.target.value}))} placeholder="e.g. Supervisor"/></div><div className="form-group"><label className="form-label">Permissions</label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}>{ALL_PERMS.map(p=>(<label key={p} style={{display:'flex',alignItems:'center',gap:8,fontSize:12.5,cursor:'pointer',padding:'6px 8px',borderRadius:7,border:`1.5px solid ${form.permissions.includes(p)?'var(--primary)':'var(--gray-200)'}`,background:form.permissions.includes(p)?'var(--primary-50)':'white',transition:'all .12s'}}><input type="checkbox" checked={form.permissions.includes(p)} onChange={()=>toggle(p)} style={{accentColor:'var(--primary)'}}/>{p.replace(/_/g,' ')}</label>))}</div></div></div><div className="modal-foot"><button className="btn btn-ghost" onClick={()=>setModal(null)}>Cancel</button><button className="btn btn-primary" onClick={save} disabled={saving}>{saving?'Saving…':'Save Role'}</button></div></div></div>)}
  </Layout>);}
